### ISSUE TITLE
does't support client  ping client directly

### ISSUE THREAD

**Issue by flyysr** [aki237/pin#5]
I set a pin server (10.10.0.1) and two pin client(10.10.0.4, and 10.10.0.5)
when i ping the 10.10.0.5 from 10.10.0.4,  the result of this ping is unreachable.
why?
Can you  help me
i look forward to your response, thanks.

**Comment by aki237** [comment]
Hey. Just saw this. I jave tried this before i was able to access the tcp ports of the other client. Probably the ICMP forwarding is not correct. Will look into it.

If you could add the routing deets of all the peers it'd be really helpful. iptables as well. 

Cheers 😀

**Comment by aelango97** [comment]
Hey, just check from my side, I was able to ping the other client. It would be helpful if you can provide the configuration from your end.

**Comment by aki237** [comment]
Hey, just checked from my side, I was able to ping the other client. It would be helpful if you can provide the configuration from your end.
